backend:
  name: github
  repo: athald0r/legapauperlipsia
  branch: main
  base_url: https://legapauperlipsia.de  # Your VPS URL
  auth_endpoint: /api/auth
media_folder: static/images
public_folder: /public
# below is fully TODO
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }